[package]
name = "integer_exponent_opencl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "benchmark_1"
path = "src/examples/benchmark_1.rs"

[dependencies]
num = "0.4"
rayon = "1.5"
opencl3 = "0.5"
